name: CI
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:   ['ubuntu', 'macos']
        python: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
      - run: |
          pytest
